#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.9.{build}.0
install:
  - git clone https://github.com/PlagueHO/DscResource.Tests

  - ps: |
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Start-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
          Start-AppveyorTestScriptTask `
            -ExcludeTag 'Examples','Markdown'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
          Start-AppveyorAfterTestTask
